### ISSUE TITLE
Radical Rex (Sega CD) - Missing character sprites in the intro, title screen, main menu etc...

### ISSUE THREAD

**Issue by Pat86** [ekeeke/Genesis-Plus-GX#290]
As written above, the Sega CD version of Radical Rex is missing character sprites in the intro, title screen, main menu and options menu -> animation test. Tested with the latest Retroarch core.

This is it running on real hardware:
https://streamable.com/66u2x

Edit: Just gave the cartridge version a try, and the sprites are there everywhere. 
So the bug only occurs to the CD version.

**Comment by ekeeke** [comment]
Indeed, never noticed this one before, this is strange. It appears it does the same in Kega Fusion (could not test in Gens as the game does not start or Picodrive) so it's either a problem with the available CD image or some unemulated/undocumented quirk being accidentally used in that game.

From a quick look, it seems like the sprite table (which contains sprites linked list with the position,size,etc of each sprites) is loaded from Word-RAM is 1M mode but Word-RAM does not contain valid sprite table data but some code or data instead and no sprites are being rendered.

**Comment by Pat86** [comment]
Since the image i used on real hardware is the same i used for emulation, i doubt there's something wrong with, otherwise it would miss the sprites on real hardware as well, or not? ;)

**Comment by ekeeke** [comment]
That I didn't know, thanks for confirming.
Can you test with Picodrive to see if it has the same issue ?

It would also be interesting to see how it behaves on FPGA emulation solution (Mega SD cartridge) if you know someone who owns one.

**Comment by Pat86** [comment]
Picodrive (via Retroarch) behaves the same as Genesis Plus GX and Kega Fusion.

Unfortunately i dont know anyone with an Mega SD cartridge.

**Comment by BooBerry** [comment]
With the MegaSD it appears to work correctly.

**Comment by Pat86** [comment]
> With the MegaSD it works correctly, all intro and title screen sprites show and the animation test works perfectly.

Just to be curious, we're talking about the CD version, right?
Because the cartridge version shows the sprites in Genesis Plus GX as well.

**Comment by BooBerry** [comment]
Correct, Sega CD (USA version) on the MegaSD tested with real hardware (and a Nomad). A second MegaSD user also confirmed it works too.

**Comment by ekeeke** [comment]
Ok, thank you for checking. 

If there are some settings in Mega SD  that affect Mega CD emulation (like seek time emulation, word-ram access slowdown, etc), I would also be interested to know if it still works correctly with them turned on/off, as this could help figuring where the issue comes from in software emulators.

**Comment by BooBerry** [comment]
The MegaSD has several options, one of them being **Emulate seek time** (which is enabled by default if I recall correctly), so I tried disabling it... and it still works. It also has an option called **Graphics scaler speedup** which when disabled simulates the original hardware Word RAM latencies... and it still works even then. Also when it's enabled, yep, it still works.

Graphics scaler speedup is explained a little bit by the developer here: https://forums.terraonion.com/viewtopic.php?f=25&t=1185#p5671

**Comment by ekeeke** [comment]
>Disabling this option makes the wordram latencies behave like original megacd, and also makes the wordram restriction in 2M mode to work like on real console when the cpu doesn't own the buffer: main 68k will just read garbage, and sub68k will halt when accessing it till it's returned. (some games rely on this feature)

This is interesting, I think I know which game is affected, I guess this gives some good reason to try again to fix it (I wasn't sure how it was supposed to behave).

Anyway, it does not look like this is the cause of the Radical Rex sprite issue if you say the option has no impact, but thanks anyway,

**Comment by Testsr** [comment]
What roms did you use to test this?

**Comment by ekeeke** [comment]
Investigating this issue recently, I noticed there is also an address error occurring on SUB CPU when the intro starts, which could be related to the same issue causing the missing sprites. The consequence is that the game is crashing at this point if address error emulation is enabled (until very recently, it was only emulated for MAIN CPU but [this](https://github.com/ekeeke/Genesis-Plus-GX/commit/c6d1e5ac38ec768fcf4a93e37dd44088473f5001) commit added address error emulation on SUB CPU).

**Comment by ekeeke** [comment]
Regarding the issue itself, it seems to be related to wrong Word-RAM / PRG-RAM initialization from CD.

I noticed the following weirdness in emulator trace log regarding CD transfers, but I cannot say if this is normal or related to these issues at all:
error.log(1363498,1)	CDC transfer sector 114 (track 0) to 0x26f0 (PT=0xE6F0, WA=0xe6f0)
error.log(1363888,1)	CDC transfer (2051 bytes) from 0x26f0 to 0x3d800 (SUB-CPU READ)
error.log(1367396,1)	CDC transfer sector 115 (track 0) to 0x3020 (PT=0xF020, WA=0xf020)
error.log(1367794,1)	CDC transfer (2051 bytes) from 0x3020 to 0x3e000 (SUB-CPU READ)
error.log(1371280,1)	CDC transfer sector 116 (track 0) to 0x3950 (PT=0xF950, WA=0xf950)
error.log(1371674,1)	CDC transfer (2051 bytes) from 0x3950 to 0x3e800 (SUB-CPU READ)
error.log(1375163,1)	CDC transfer sector 117 (track 0) to 0x280 (PT=0x280, WA=0x280)
error.log(1375554,1)	CDC transfer (2051 bytes) from 0x280 to 0x3f000 (SUB-CPU READ)
error.log(1379061,1)	CDC transfer sector 118 (track 0) to 0xbb0 (PT=0xBB0, WA=0xbb0)
error.log(1379459,1)	CDC transfer (2051 bytes) from 0xbb0 to 0x3f800 (SUB-CPU READ)
**error.log(1382945,1)	CDC transfer sector 119 (track 0) to 0x14e0 (PT=0x14E0, WA=0x14e0)
error.log(1383165,1)	CDC transfer (2047 bytes) from 0x14e4 to 0x0 (WORD-RAM DMA)
error.log(1383832,1)	CDC transfer sector 120 (track 0) to 0x1e10 (PT=0x1E10, WA=0x1e10)
error.log(1384231,1)	CDC transfer (2051 bytes) from 0x1e10 to 0x40000 (SUB-CPU READ)
error.log(1387726,1)	CDC transfer sector 121 (track 0) to 0x2740 (PT=0x2740, WA=0x2740)
error.log(1388540,1)	CDC transfer sector 122 (track 0) to 0x3070 (PT=0x3070, WA=0x3070)
error.log(1389011,1)	CDC transfer (2051 bytes) from 0x3070 to 0x40000 (SUB-CPU READ)
error.log(1392505,1)	CDC transfer sector 123 (track 0) to 0x39a0 (PT=0x39A0, WA=0x39a0)
error.log(1392899,1)	CDC transfer (2051 bytes) from 0x39a0 to 0x40000 (SUB-CPU READ)
error.log(1410967,1)	CDC transfer sector 62 (track 0) to 0x930 (PT=0x930, WA=0x930)
error.log(1411685,1)	CDC transfer sector 63 (track 0) to 0x1260 (PT=0x1260, WA=0x1260)
error.log(1412085,1)	CDC transfer (2051 bytes) from 0x1260 to 0x40000 (SUB-CPU READ)**
error.log(1415570,1)	CDC transfer sector 64 (track 0) to 0x1b90 (PT=0x1B90, WA=0x1b90)
error.log(1415965,1)	CDC transfer (2051 bytes) from 0x1b90 to 0x40800 (SUB-CPU READ)
error.log(1419454,1)	CDC transfer sector 65 (track 0) to 0x24c0 (PT=0x24C0, WA=0x24c0)
error.log(1419844,1)	CDC transfer (2051 bytes) from 0x24c0 to 0x41000 (SUB-CPU READ)

**Comment by ekeeke** [comment]
Yes, maybe. At this point, it is hard to figure what the game is doing wrong in emulators and what it should be doing. It is not helping that only proprietary FPGA implementation get this one right. I wonder if it works in Mister FPGA core ? If it does, a log of CDC access (from disc to CDC RAM and from CDC RAM to Word-RAM and PRG-RAM) could help what is wrong with this game in software emulators :-/

**Comment by Pat86** [comment]
FYI: the latest BlastEm version emulates it flawlessly. All sprites are there.

**Comment by ekeeke** [comment]
Interesting, thanks for the notice. Do you know if it ever had the issue in older build ? It could help figuring what is the cause for it and what is wrong in other emularors ?

**Comment by Pat86** [comment]
Unfortunately no, i just saw that it supports CD games now, so i tried the game with the latest build. but i dont know since when it does.

**Comment by ekeeke** [comment]
Too bad. But it as a debugger so it can be helpfu. Thanks anyway.
It seems there is also now Ares emulator with quite good Mega CD compatibility, might be worth checking it as well.

**Comment by Pat86** [comment]
Just gave Ares a try and it's still broken in the current build. Sprites are missing just like here.

**Comment by ekeeke** [comment]
> FYI: the latest BlastEm version (nightly builds) emulates it flawlessly. All sprites are there.

Trying Blastem lates build (win64), it freezes during Sega CD boot animation. Is there a preferred BIOS version ?

**Comment by Tasosgemah** [comment]
The game doesn't start anymore, it hangs on a black screen.

**Comment by irixxxx** [comment]
I can share some information regarding this:

- on starting the game, the sub CPU is loading 192 blocks, from 61 on, to address 0x24000
- Each sector generates a level 5 irq. The irq 5 handler has 2 stages, one in the lower BIOS, and an upper half. The upper code pushes a fake irq frame to make the lower half returning to the upper half on completion.
- the lower half will put the lba information into the cdc receive ring buffer after a block has been received. 
- the upper half checks for the long value at 0x3fffc being not zero, an additional flag being zero which is set in the upper half if at work, and also if the BIOS's cdc receive ring buffer contains something. If so, it initiates a cdc DMA transfer. It seems to be part of a background loading mechanism.
- however, the sub CPU loader loads data at 0x3f800-0x3ffff at block 119 which puts a 0xffffffff value at 0x3fffc. Now, all conditions for the upper half irq 5 handler to take over are met. It then interferes with the loader because it initiates a DMA transfer on its own, messing the loader.
- there's some error catcher code which is somehow triggered and restarts the transfer in the BIOS from block 61 which is kicking in at some point. However, since the loader doesn't know about this, instead of loading the data at 0x24000 it is now loaded at 0x40000, putting wrong data into the upper program RAM half. That in turn leads to the missing sprites.

I haven't however uncovered yet why this is behaving differently on real hardware.

**Comment by ekeeke** [comment]
Thanks for the deeper analysis, I more or less gave up on this one as debugging Mega CD software is kinda difficult with the limited logs I have without knowing exactly what is going on but this gives some new hints about what could cause this issue or at least where to focus the debugging. 

Could you however precise what you mean by
>The irq 5 handler has 2 stages, one in the lower BIOS, and an upper half.The upper code pushes a fake irq frame to make the lower half returning to the upper half on completion.

as I'm not sure to understand what you exactly mean by "lower" and "upper" half ?

**Comment by irixxxx** [comment]
The irq 5 handler points to what I called "upper half". It has this code at the beginning:
```    638e:       48e7 f0fc       moveml %d0-%d3/%a0-%a5,%sp@-
    6392:       2a7c 00ff 8000  moveal #16744448,%a5
    6398:       2f3c 0000 63a8  movel #25512,%sp@-
    639e:       40e7            movew %sr,%sp@-
    63a0:       2479 0000 6236  moveal 0x6236,%a2
    63a6:       4ed2            jmp %a2@
    63a8:       4ab9 0003 fffc  tstl 0x3fffc
    63ae:       6700 0144       beqw 0x64f4
```
This is calling the BIOS irq 5 handler whose address has been stored in 0x6236. Since that ends with an rte instruction as well, it pushes a fake interrupt stack frame which returns to the instruction after the jmp.

I might be a tiny bit further with the investigation. I think it might be related to real hardware possibly having the cdc decoder return data before the lba which was addressed by the play command. I'm currently trying to fake that behaviour.
I observed writes to the cdd command reg on real hardware and noticed it writes the play command 3 times, while in the emu it only does so 2 times. blastem also shows this behaviour. I reckon some error counter is overflowing with the early blocks coming in from the BIOS error catcher, so the loader is actually initiating another retry.

**Comment by ekeeke** [comment]
>I think it might be related to real hardware possibly having the cdc decoder return data before the lba which was addressed by the play command.

This is actually the case, yes. The CDD starts reading data 3 sectors before the one addressed by the PLAY command, you can see it in Krikzz's CDD logs done on real Mzga-CD hardware,  see for example https://github.com/krikzz/MEGA-PRO/blob/master/mcd-verificator/cd-log/BI-mcd-tst/read-sector-bios.txt). I don't emulate this yet accurately (only fake it by returning CDD status at 0x01 when cdd.latency is < 3).

**Comment by irixxxx** [comment]
I added a quickhack for emulating the early decoder interrupts without loading the data for it. I now see the duplicated start, but it's still now working. There must be something else to it.

FYI, this is the loader code:

```
    6584:       4e56 fffc       linkw %fp,#-4           ;; loader(lba, count, dst)
    6588:       48e7 7cc0       moveml %d1-%d5/%a0-%a1,%sp@-
    658c:       383c 0005       movew #5,%d4
    6590:       7aff            moveq #-1,%d5
; loop
    6592:       5384            subql #1,%d4
    6594:       6700 0082       beqw 0x6618
    6598:       323c 0000       movew #0,%d1
    659c:       303c 0096       movew #150,%d0
    65a0:       4eb8 5f22       jsr 0x5f22              ;; 1: cdcsetmode(0)
    65a4:       262e 0008       movel %fp@(8),%d3       ;; lba
    65a8:       242e 000c       movel %fp@(12),%d2      ;; count
    65ac:       41ee 0008       lea %fp@(8),%a0         ;; &lba
    65b0:       303c 0020       movew #32,%d0
    65b4:       4eb8 5f22       jsr 0x5f22              ;; queuecmd, 2 args
    65b8:       4eb9 0000 6360  jsr 0x6360              ;; wait for data
    65be:       303c 008a       movew #138,%d0
    65c2:       4eb8 5f22       jsr 0x5f22              ;; 2: cdcstat
    65c6:       65f0            bcss 0x65b8
    65c8:       026d f8ff 0004  andiw #-1793,%a5@(4)
    65ce:       006d 0300 0004  oriw #768,%a5@(4)
    65d4:       303c 008b       movew #139,%d0
    65d8:       4eb8 5f22       jsr 0x5f22              ;; cdcread
    65dc:       65b4            bcss 0x6592
    65de:       206e 0010       moveal %fp@(16),%a0     ;; dst
    65e2:       43ee fffc       lea %fp@(-4),%a1        ;; &lba
    65e6:       303c 008c       movew #140,%d0
    65ea:       4eb8 5f22       jsr 0x5f22              ;; cdctrn(dst,&lba)
    65ee:       65a2            bcss 0x6592
    65f0:       303c 008d       movew #141,%d0
    65f4:       4eb8 5f22       jsr 0x5f22              ;; cdcack
    65f8:       202e fffc       movel %fp@(-4),%d0
    65fc:       0280 ffff ff00  andil #-256,%d0
    6602:       4eb9 0000 630e  jsr 0x630e              ;; lba->bin
    6608:       b680            cmpl %d0,%d3
    660a:       6686            bnes 0x6592             ;; -> 1
    660c:       2d48 0010       movel %a0,%fp@(16)
    6610:       5283            addql #1,%d3
    6612:       5382            subql #1,%d2
    6614:       66a8            bnes 0x65be             ;; -> 2
    6616:       7a00            moveq #0,%d5
    6618:       2005            movel %d5,%d0
    661a:       4cdf 033e       moveml %sp@+,%d1-%d5/%a0-%a1
    661e:       4e5e            unlk %fp
    6620:       4e75            rts
```

and it is called from here:

```
    8082:       2f08            movel %a0,%sp@-
    8084:       4879 0002 4000  pea 0x24000
    808a:       4878 00b8       pea 0xb8
    808e:       4878 003f       pea 0x3f
    8092:       2078 7ffc       moveal 0x7ffc,%a0
    8096:       2068 0040       moveal %a0@(64),%a0
    809a:       4e90            jsr %a0@
    809c:       defc 000c       addaw #12,%sp
    80a0:       205f            moveal %sp@+,%a0
    80a2:       4a00            tstb %d0
    80a4:       6708            beqs 0x80ae
    80a6:       4eb9 0000 6174  jsr 0x6174
    80ac:       60d4            bras 0x8082
 ```

**Comment by irixxxx** [comment]
I think the culprit is that in the real hardware irq 4 seems to come some time before irq 5, but in both PicoDrive and GX they come at the same time, so irq 5 is handled first. As it is, the irq 4 handler can snatch away information put by the irq 5 handler in the cdc receive ring buffer before the loader can get to it. That's happening after the dma transfer trashed the state, and that seems to lead to the loader not seeing enough erroneous attempts for starting over the complete transfer.

**Comment by ekeeke** [comment]
Indeed, both interrupts are triggered at the same time in the emulator as it was simpler to do (as both are supposed to have same frequency)  and it worked fine for all BIOSes and games I tested but maybe this is one of the edge case where more accurate interrupt timings are needed.

This is one of the things that are emulated more accurately in Blastem for sure and there is certainly some delay between the two interrupts on real hardware but I am not 100% sure about the timings (one is triggered when cdd sends its last status word while the other is triggered when cdc decodes received block but it is no clear when these two events happen related to each other). It would be helpful to have real hardware traces with the two interrupts being loggued but I've never found such logs anywhere.

**Comment by irixxxx** [comment]
Hmm, from my measurements on the 68K IPL lines during the loader I'd say it's roughly 3ms. I didn't take exact timings though. It's however still not working with a quick hack in place. This is getting rather annoying.

**Comment by irixxxx** [comment]
I got it running. The key to this is that in case of a new play command to the CDD, the next 2 blocks are still decoded before the seek to the new position starts. At least that's what blastem does. I'll maybe go and write some test to verify this.

I added a quickhack for playing out one additional block, and that alone will produce the needed erroneous transfers for the loader to detect failure and restart the complete transfer.
All the other stuff (start decoding 3 blocks before the lba requested, different timing for irq4/5) isn't necessary for it, though I might keep it now that it's there.

**Comment by ekeeke** [comment]
Wow, good job at finding a working solution for this one. Yes, it makes sense that seeking does not start immediately when the command is received and that there is some latency within the CD drive parts that makes a few sectors still being read and sent to CDC before seeking really starts but I would never have thought this would fix that particular issue so thank you for your work !

I am not able to test it for the moment as I don't have access to my computer but will make sure to try this in a few days... and hopefully finally close this long-standing issue.

**Comment by irixxxx** [comment]
I did some analysis of what blastem is doing and I think I can explain why this appears to be 2 blocks overhang:
- the new command is sent in irq 4
- it takes some time to decode and process the command
- meanwhile, the current block in decode has finished and the next block has started
- there's probably no logic to stop decoding by Occam's Razor, so it finished that block as well before starting the seek
So, 2 indeed makes sense in this special setup. In other setups it might only be one.

**Comment by ekeeke** [comment]
Yes,  on real hardware, CD data stream is not directly controlled by CDD but goes straight from CD DSP (CXDxxx chip) to CD data decoder (LC8951x chip) so CD data sectors are continuously decoded by CDC (provided decoding is enabled) independently from CDD processing and seeking (or pausing) does not have immediate effect on CD data stream as commands sent by CDD to other CD drive chips which control the laser beam positioning needs to be processed and have some physical delay.

In fact, if you look at some of Krikzz's CD logs, you can see that when a pause command is received by CDD from SUB-CPU while the disc is being read (cdd status = 0x1), cdd status changes imediately to paused status (0x4) but the reported position (in other cdd status nibbles) continues to increase for two sectors before it seeks back to a few sectors before the paused position , which means CDD continues  to receive valid subcode data from CD-DSP for two sectors before seeking occurs, and by extension, CDC probably also receives the two next sectors. See https://github.com/krikzz/MEGA-PRO/blob/master/mcd-verificator/cd-log/BI-mcd-tst/read-sector-bios.txt#L178 for example but it seems to be constantly 2 sectors delay in other logs for this use case.

**Comment by ekeeke** [comment]
Pushed a fix in https://github.com/ekeeke/Genesis-Plus-GX/commit/dd619513a4a7136e7279cbf6adb660ac30598bdd

Thanks again for the help !

**Comment by irixxxx** [comment]
You are welcome, it's however also benefitting picodrive. I took a slightly different approach at executing cdd commands delayed, but I guess the basic idea is the same.

**Comment by Tasosgemah** [comment]
> it's however also benefitting picodrive

Is Picodrive active? It's github page shows the last commit was 2 years ago...

**Comment by irixxxx** [comment]
look at https://github.com/irixxxx/picodrive.
